

"""Module contains classes defining objects for parsing and indexing cytological profiling data.
"""

from scipy.stats import pearsonr
import sys
import numpy
from progressbar import ProgressBar, Percentage, Bar, RotatingMarker, ETA, FileTransferSpeed
from scipy.optimize import curve_fit

import matplotlib
matplotlib.use("pdf")
import matplotlib.pyplot as plt

labels = "MICRO_AND_BINUCLEATED_CELLS_MICRONUCLEI_EDU	MICRO_AND_PROBEABPOSITIVE_CELLS_MICRONUCLEI_EDU	MICRO_AND_PROBEBPOSITIVE_CELLS_MICRONUCLEI_EDU	MICRO_AND_PROBEAPOSITIVE_CELLS_MICRONUCLEI_EDU	INTERPHASE_CELLS_MICRONUCLEI_EDU	MONONUCLEATED_CELLS_MICRONUCLEI_EDU	BINUCLEATED_CELLS_MICRONUCLEI_EDU	MICRONUCLEATED_CELLS_MICRONUCLEI_EDU	CELLS_WITH_ONE_MICRONUCLEUS_MICRONUCLEI_EDU	PCT_BINUCLEATED_CELLS_MICRONUCLEI_EDU	NUCLEAR_DIVISION_INDEX_MICRONUCLEI_EDU	PCT_CELLS_WITH_ONE_MICRONUCLEUS_MICRONUCLEI_CYTO	PCT_MICRONUCLEATED_CELLS_MICRONUCLEI_CYTO	MICRONUCLEI_PER_CELL_MICRONUCLEI_CYTO	TOTAL_MICRONUCLEI_MICRONUCLEI_CYTO	ALL_ACTIN_MEAN_NUCL_INTEGR_INTENS_MULTIWAVESCORING_CYTO	POSITIVE_ACTIN_MEAN_NUCL_INTEGR_INTENS_MULTIWAVESCORING_CYTO	ALL_ACTIN_MEAN_STAIN_INTEGR_INTENS_MULTIWAVESCORING_CYTO	POSITIVE_ACTIN_MEAN_STAIN_INTEGR_INTENS_MULTIWAVESCORING_CYTO	ALL_ACTIN_MEAN_STAIN_AREA_MULTIWAVESCORING_CYTO	POSITIVE_ACTIN_MEAN_STAIN_AREA_MULTIWAVESCORING_CYTO	POSITIVE_TUBULIN_MEAN_NUCL_INTEGR_INTENS_MULTIWAVESCORING_CYTO	ALL_TUBULIN_MEAN_NUCL_INTEGR_INTENS_MULTIWAVESCORING_CYTO	CELL_TUBULIN_NUCLEUS_INTEGR_INTENSITY_MULTIWAVESCORING_CYTO	DNA_MEAN_AREA_MICRONUCLEI_EDU	BREADTH_IMA_SUMMARY_CYTO	INNER_RADIUS_IMA_SUMMARY_CYTO	OUTER_RADIUS_IMA_SUMMARY_CYTO	LENGTH_IMA_SUMMARY_CYTO	PERIMETER_IMA_SUMMARY_CYTO	MEAN_RADIUS_IMA_SUMMARY_CYTO	EQUIV_RADIUS_IMA_SUMMARY_CYTO	EQUIV_PROLATE_VOL_IMA_SUMMARY_CYTO	ALL_NUCLEI_MEAN_AREA_MULTIWAVESCORING_CYTO	AREA_IMA_SUMMARY_CYTO	EQUIV_SPHERE_SURFACE_AREA_IMA_SUMMARY_CYTO	TOTAL_AREA_IMA_SUMMARY_CYTO	PIXEL_AREA_IMA_SUMMARY_CYTO	EQUIV_SPHERE_VOL_IMA_SUMMARY_CYTO	EQUIV_OBLATE_VOL_IMA_SUMMARY_CYTO	NEGATIVE_EDU_MEAN_CELL_INTEGR_INTENS_MULTIWAVESCORING_EDU	NEGATIVE_EDU_MEAN_NUCL_INTEGR_INTENS_MULTIWAVESCORING_EDU	OUTER_RADIUS_IMA_SUMMARY_EDU	LENGTH_IMA_SUMMARY_EDU	EQUIV_SPHERE_VOL_IMA_SUMMARY_EDU	EQUIV_OBLATE_VOL_IMA_SUMMARY_EDU	EQUIV_PROLATE_VOL_IMA_SUMMARY_EDU	DAPI_STAINED_AREA_MULTIWAVESCORING_EDU	CELL_TOTAL_AREA_MULTIWAVESCORING_EDU	WIDTH_IMA_SUMMARY_EDU	PERIMETER_IMA_SUMMARY_EDU	EQUIV_RADIUS_IMA_SUMMARY_EDU	MEAN_RADIUS_IMA_SUMMARY_EDU	ALL_CELLS_MEAN_AREA_MULTIWAVESCORING_EDU	ALL_NUCLEI_MEAN_AREA_MULTIWAVESCORING_EDU	PIXEL_AREA_IMA_SUMMARY_EDU	EQUIV_SPHERE_SURFACE_AREA_IMA_SUMMARY_EDU	AREA_IMA_SUMMARY_EDU	TOTAL_AREA_IMA_SUMMARY_EDU	NUCLEAR_AREA_PER_CELL_TRANSFLUOR_EDU	INNER_RADIUS_IMA_SUMMARY_EDU	BREADTH_IMA_SUMMARY_EDU	ALL_PH3_MEAN_CELL_AVER_INTENS_MULTIWAVESCORING_EDU	ALL_PH3_MEAN_NUCL_AVER_INTENS_MULTIWAVESCORING_EDU	ALL_PH3_MEAN_NUCL_INTEGR_INTENS_MULTIWAVESCORING_EDU	ALL_PH3_MEAN_CELL_INTEGR_INTENS_MULTIWAVESCORING_EDU	NEGATIVE_PH3_MEAN_CELL_INTEGR_INTENS_MULTIWAVESCORING_EDU	NEGATIVE_PH3_MEAN_NUCL_INTEGR_INTENS_MULTIWAVESCORING_EDU	PCT_CELLS_WITH_MULTI_MICRONUCLEI_MICRONUCLEI_EDU	ALL_EDU_MEAN_STAIN_AREA_MULTIWAVESCORING_EDU	PCT_POSITIVE_EDU_MULTIWAVESCORING_EDU	CELL_PH3_STAINED_AVERAGE_INTENSITY_MULTIWAVESCORING_CYTO	CELL_PH3_STAINED_AVERAGE_INTENSITY_MULTIWAVESCORING_EDU	NEGATIVE_PH3_MEAN_STAIN_AREA_MULTIWAVESCORING_EDU	NEGATIVE_PH3_MEAN_STAIN_INTEGR_INTENS_MULTIWAVESCORING_EDU	POSITIVE_ACTIN_MEAN_CELL_AVER_INTENS_MULTIWAVESCORING_CYTO	ALL_ACTIN_MEAN_CELL_AVER_INTENS_MULTIWAVESCORING_CYTO	POSITIVE_ACTIN_MEAN_CYTO_AVER_INTENS_MULTIWAVESCORING_CYTO	ALL_ACTIN_MEAN_CYTO_AVER_INTENS_MULTIWAVESCORING_CYTO	PIT_INTEGRATED_INTENSITY_TRANSFLUOR_CYTO	PIT_COUNT_TRANSFLUOR_CYTO	PIT_TOTAL_AREA_TRANSFLUOR_CYTO	GRADIENT_INDEX_TRANSFLUOR_CYTO	LAPLACIAN_INDEX_TRANSFLUOR_CYTO	POSITIVE_TUBULIN_MEAN_CYTO_AVER_INTENS_MULTIWAVESCORING_CYTO	ALL_TUBULIN_MEAN_CYTO_AVER_INTENS_MULTIWAVESCORING_CYTO	ALL_TUBULIN_MEAN_STAIN_AVER_INTENS_MULTIWAVESCORING_CYTO	POSITIVE_TUBULIN_MEAN_STAIN_AVER_INTENS_MULTIWAVESCORING_CYTO	ALL_TUBULIN_MEAN_CELL_AVER_INTENS_MULTIWAVESCORING_CYTO	POSITIVE_TUBULIN_MEAN_CELL_AVER_INTENS_MULTIWAVESCORING_CYTO	NEGATIVE_ACTIN_MEAN_NUCL_INTEGR_INTENS_MULTIWAVESCORING_CYTO	NEGATIVE_ACTIN_MEAN_STAIN_AVER_INTENS_MULTIWAVESCORING_CYTO	NEGATIVE_ACTIN_MEAN_CYTO_AVER_INTENS_MULTIWAVESCORING_CYTO	NEGATIVE_ACTIN_MEAN_CELL_AVER_INTENS_MULTIWAVESCORING_CYTO	NEGATIVE_ACTIN_MEAN_NUCL_AVER_INTENS_MULTIWAVESCORING_CYTO	MITOTIC_CELLS_MICRONUCLEI_CYTO	TOTAL_CELLS_MICRONUCLEI_CYTO	TOTAL_CELLS_MULTIWAVESCORING_CYTO	POSITIVE_TUBULIN_MULTIWAVESCORING_CYTO	POSITIVE_ACTIN_MULTIWAVESCORING_CYTO	DNA_TOTAL_AREA_MICRONUCLEI_CYTO	INTERPHASE_CELLS_MICRONUCLEI_CYTO	MONONUCLEATED_CELLS_MICRONUCLEI_CYTO	MITOTIC_CELLS_MICRONUCLEI_EDU	POSITIVE_EDU_MULTIWAVESCORING_EDU	PIT_TOTAL_AREA_TRANSFLUOR_EDU	PIT_COUNT_TRANSFLUOR_EDU	NUCLEAR_INTEGRATED_INTENSITY_TRANSFLUOR_EDU	NUCLEAR_TOTAL_AREA_TRANSFLUOR_EDU	DNA_TOTAL_AREA_MICRONUCLEI_EDU	TOTAL_CELLS_MICRONUCLEI_EDU	TOTAL_CELLS_MULTIWAVESCORING_EDU	NUCLEAR_COUNT_TRANSFLUOR_EDU	ELL_FORM_FACTOR_IMA_SUMMARY_CYTO	ELL_FORM_FACTOR_IMA_SUMMARY_EDU	NEGATIVE_PH3_MEAN_STAIN_AVER_INTENS_MULTIWAVESCORING_EDU	ALL_PH3_MEAN_STAIN_INTEGR_INTENS_MULTIWAVESCORING_EDU	ALL_PH3_MEAN_STAIN_AREA_MULTIWAVESCORING_EDU	PCT_POSITIVE_PH3_MULTIWAVESCORING_EDU	POSITIVE_PH3_MULTIWAVESCORING_EDU	POSITIVE_PH3_MULTIWAVESCORING_CYTO	PCT_POSITIVE_PH3_MULTIWAVESCORING_CYTO	ALL_PH3_MEAN_STAIN_AREA_MULTIWAVESCORING_CYTO	ALL_PH3_MEAN_STAIN_INTEGR_INTENS_MULTIWAVESCORING_CYTO	NEGATIVE_PH3_MEAN_STAIN_AREA_MULTIWAVESCORING_CYTO	NEGATIVE_PH3_MEAN_STAIN_INTEGR_INTENS_MULTIWAVESCORING_CYTO	PIT_AVERAGE_INTENSITY_TRANSFLUOR_EDU	NEGATIVE_EDU_MEAN_STAIN_AVER_INTENS_MULTIWAVESCORING_EDU	CELL_PROBEA_AVERAGE_INTENSITY_MICRONUCLEI_EDU	CELL_EDU_NUCLEUS_AVERAGE_INTENSITY_MULTIWAVESCORING_EDU	CELL_EDU_CELL_AVERAGE_INTENSITY_MULTIWAVESCORING_EDU	ALL_EDU_MEAN_CELL_INTEGR_INTENS_MULTIWAVESCORING_EDU	ALL_EDU_MEAN_NUCL_INTEGR_INTENS_MULTIWAVESCORING_EDU	ALL_EDU_MEAN_STAIN_INTEGR_INTENS_MULTIWAVESCORING_EDU	POSITIVE_EDU_MEAN_CELL_AVER_INTENS_MULTIWAVESCORING_EDU	POSITIVE_EDU_MEAN_NUCL_AVER_INTENS_MULTIWAVESCORING_EDU	ALL_EDU_MEAN_STAIN_AVER_INTENS_MULTIWAVESCORING_EDU	POSITIVE_EDU_MEAN_STAIN_AVER_INTENS_MULTIWAVESCORING_EDU	POSITIVE_EDU_MEAN_STAIN_INTEGR_INTENS_MULTIWAVESCORING_EDU	POSITIVE_EDU_MEAN_CELL_INTEGR_INTENS_MULTIWAVESCORING_EDU	POSITIVE_EDU_MEAN_NUCL_INTEGR_INTENS_MULTIWAVESCORING_EDU	CELLULAR_GRADIENT_INDEX_TRANSFLUOR_EDU	CELLULAR_LAPLACIAN_INDEX_TRANSFLUOR_EDU	PIT_INTEGRATED_INTENSITY_TRANSFLUOR_EDU	ALL_EDU_MEAN_NUCL_AVER_INTENS_MULTIWAVESCORING_EDU	ALL_EDU_MEAN_CELL_AVER_INTENS_MULTIWAVESCORING_EDU	CELLULAR_TEXTURE_INDEX_TRANSFLUOR_EDU	LAPLACIAN_INDEX_TRANSFLUOR_EDU	GRADIENT_INDEX_TRANSFLUOR_EDU	TEXTURE_INDEX_TRANSFLUOR_EDU	CELL_EDU_STAINED_AVERAGE_INTENSITY_MULTIWAVESCORING_EDU	POSITIVE_EDU_MEAN_STAIN_AREA_MULTIWAVESCORING_EDU	CELL_EDU_STAINED_AREA_MULTIWAVESCORING_EDU	POSITIVE_PH3_MEAN_STAIN_AREA_MULTIWAVESCORING_EDU	NEGATIVE_PH3_MEAN_STAIN_AVER_INTENS_MULTIWAVESCORING_CYTO	POSITIVE_PH3_MEAN_CYTO_AVER_INTENS_MULTIWAVESCORING_CYTO	POSITIVE_PH3_MEAN_CELL_AVER_INTENS_MULTIWAVESCORING_CYTO	POSITIVE_PH3_MEAN_STAIN_AREA_MULTIWAVESCORING_CYTO	ALL_PH3_MEAN_STAIN_AVER_INTENS_MULTIWAVESCORING_CYTO	POSITIVE_PH3_MEAN_NUCL_INTEGR_INTENS_MULTIWAVESCORING_CYTO	POSITIVE_PH3_MEAN_STAIN_INTEGR_INTENS_MULTIWAVESCORING_CYTO	POSITIVE_PH3_MEAN_STAIN_AVER_INTENS_MULTIWAVESCORING_CYTO	POSITIVE_PH3_MEAN_NUCL_AVER_INTENS_MULTIWAVESCORING_CYTO	POSITIVE_PH3_MEAN_CELL_INTEGR_INTENS_MULTIWAVESCORING_EDU	POSITIVE_PH3_MEAN_NUCL_INTEGR_INTENS_MULTIWAVESCORING_EDU	POSITIVE_PH3_MEAN_STAIN_INTEGR_INTENS_MULTIWAVESCORING_EDU	POSITIVE_PH3_MEAN_STAIN_AVER_INTENS_MULTIWAVESCORING_EDU	POSITIVE_PH3_MEAN_NUCL_AVER_INTENS_MULTIWAVESCORING_EDU	POSITIVE_PH3_MEAN_CELL_AVER_INTENS_MULTIWAVESCORING_EDU	ALL_PH3_MEAN_STAIN_AVER_INTENS_MULTIWAVESCORING_EDU	NEGATIVE_TUBULIN_MEAN_NUCL_AVER_INTENS_MULTIWAVESCORING_CYTO	NEGATIVE_TUBULIN_MEAN_CELL_AVER_INTENS_MULTIWAVESCORING_CYTO	NEGATIVE_TUBULIN_MEAN_CYTO_AVER_INTENS_MULTIWAVESCORING_CYTO	NEGATIVE_TUBULIN_MEAN_STAIN_INTEGR_INTENS_MULTIWAVESCORING_CYTO	NEGATIVE_TUBULIN_MEAN_STAIN_AREA_MULTIWAVESCORING_CYTO	NEGATIVE_TUBULIN_MEAN_STAIN_AVER_INTENS_MULTIWAVESCORING_CYTO	NEGATIVE_TUBULIN_MEAN_NUCL_INTEGR_INTENS_MULTIWAVESCORING_CYTO	NEGATIVE_TUBULIN_MEAN_CELL_INTEGR_INTENS_MULTIWAVESCORING_CYTO	PCT_POSITIVE_TUBULIN_MULTIWAVESCORING_CYTO	BINUCLEATED_CELLS_MICRONUCLEI_CYTO	MULTINUCLEATED_CELLS_MICRONUCLEI_CYTO	MULTIMONO_CELL_RATIO_MICRONUCLEI_CYTO	MULTIDUALMONO_CELL_RATIO_MICRONUCLEI_CYTO	DUALMONO_CELL_RATIO_MICRONUCLEI_CYTO	PCT_BINUCLEATED_CELLS_MICRONUCLEI_CYTO	MULTIDUALMONO_CELL_RATIO_MICRONUCLEI_EDU	DUALMONO_CELL_RATIO_MICRONUCLEI_EDU	DNA_MEAN_AREA_MICRONUCLEI_CYTO	ALL_PH3_MEAN_NUCL_INTEGR_INTENS_MULTIWAVESCORING_CYTO	CELL_ACTIN_CYTOPLASM_AVERAGE_INTENSITY_MULTIWAVESCORING_CYTO	CELL_ACTIN_CELL_AVERAGE_INTENSITY_MULTIWAVESCORING_CYTO	NEGATIVE_ACTIN_MEAN_STAIN_INTEGR_INTENS_MULTIWAVESCORING_CYTO	NEGATIVE_ACTIN_MEAN_STAIN_AREA_MULTIWAVESCORING_CYTO	PCT_CELLS_WITH_MULTI_MICRONUCLEI_MICRONUCLEI_CYTO	SHAPE_FACTOR_IMA_SUMMARY_CYTO	PCT_PROBEA_POSITIVE_CELLS_MICRONUCLEI_EDU	PCT_PROBEB_POSITIVE_CELLS_MICRONUCLEI_EDU	PCT_PROBEAB_POSITIVE_CELLS_MICRONUCLEI_EDU	PCT_CELLS_WITH_ONE_MICRONUCLEUS_MICRONUCLEI_EDU	PCT_MICRONUCLEATED_CELLS_MICRONUCLEI_EDU	MICRONUCLEI_PER_CELL_MICRONUCLEI_EDU	MICRONUCLEI_PER_HEALTHY_CELL_MICRONUCLEI_EDU	MICRONUCLEI_PER_MONONUCLEATED_CELL_MICRONUCLEI_CYTO	MICRONUCLEI_PER_PROBEBPOSITIVE_CELL_MICRONUCLEI_EDU	MICRONUCLEI_PER_PROBEABPOSITIVE_CELL_MICRONUCLEI_EDU	MICRONUCLEI_PER_PROBEAPOSITIVE_CELL_MICRONUCLEI_EDU	MICRONUCLEI_PER_MONONUCLEATED_CELL_MICRONUCLEI_EDU	NEGATIVE_EDU_MEAN_STAIN_AREA_MULTIWAVESCORING_EDU	NEGATIVE_EDU_MEAN_STAIN_INTEGR_INTENS_MULTIWAVESCORING_EDU	CELLS_WITH_MULTI_MICRONUCLEI_MICRONUCLEI_CYTO	CELL_ACTIN_NUCLEUS_AVERAGE_INTENSITY_MULTIWAVESCORING_CYTO	CELL_ACTIN_STAINED_AVERAGE_INTENSITY_MULTIWAVESCORING_CYTO	TEXTURE_INDEX_TRANSFLUOR_CYTO	PIT_AVERAGE_INTENSITY_TRANSFLUOR_CYTO	CELL_TUBULIN_CELL_AVERAGE_INTENSITY_MULTIWAVESCORING_CYTO	ALL_TUBULIN_MEAN_NUCL_AVER_INTENS_MULTIWAVESCORING_CYTO	POSITIVE_TUBULIN_MEAN_NUCL_AVER_INTENS_MULTIWAVESCORING_CYTO	CELLULAR_GRADIENT_INDEX_TRANSFLUOR_CYTO	CELL_GRADIENT_INDEX_TRANSFLUOR_CYTO	CELL_LAPLACIAN_INDEX_TRANSFLUOR_CYTO	CELL_TEXTURE_INDEX_TRANSFLUOR_CYTO	CELL_TUBULIN_NUCLEUS_AVERAGE_INTENSITY_MULTIWAVESCORING_CYTO	CELL_PIT_AVERAGE_INTENSITY_TRANSFLUOR_CYTO	PIT_COUNT_PER_CELL_TRANSFLUOR_CYTO	PIT_AREA_PER_CELL_TRANSFLUOR_CYTO	POSITIVE_ACTIN_MEAN_NUCL_AVER_INTENS_MULTIWAVESCORING_CYTO	MULTINUCLEATED_CELLS_MICRONUCLEI_EDU	MULTIMONO_CELL_RATIO_MICRONUCLEI_EDU	PCT_MULTINUCLEATED_CELLS_MICRONUCLEI_EDU	CELLS_WITH_MULTI_MICRONUCLEI_MICRONUCLEI_EDU	ALL_NUCLEI_MEAN_INTEGR_ITENSITY_MULTIWAVESCORING_EDU	TOTAL_INTENSITY_IMA_SUMMARY_EDU	ALL_NUCLEI_MEAN_INTEGR_ITENSITY_MULTIWAVESCORING_CYTO	TOTAL_INTENSITY_IMA_SUMMARY_CYTO	PCT_MITOTIC_CELLS_MICRONUCLEI_EDU	ALL_NUCLEI_MEAN_AVERAGE_ITENSITY_MULTIWAVESCORING_CYTO	AVERAGE_INTENSITY_IMA_SUMMARY_CYTO	CELL_DNA_AVERAGE_INTENSITY_MICRONUCLEI_CYTO	CELL_NUCLEAR_AVERAGE_INTENSITY_MICRONUCLEI_CYTO	DAPI_AVERAGE_INTENSITY_MULTIWAVESCORING_CYTO	CELL_NUCLEAR_AVERAGE_INTENSITY_TRANSFLUOR_CYTO	CELL_DNA_AVERAGE_INTENSITY_MICRONUCLEI_EDU	CELL_NUCLEAR_AVERAGE_INTENSITY_MICRONUCLEI_EDU	CELL_NUCLEAR_AVERAGE_INTENSITY_TRANSFLUOR_EDU	DAPI_AVERAGE_INTENSITY_MULTIWAVESCORING_EDU	NUCLEAR_AVERAGE_INTENSITY_TRANSFLUOR_EDU	ALL_NUCLEI_MEAN_AVERAGE_ITENSITY_MULTIWAVESCORING_EDU	AVERAGE_INTENSITY_IMA_SUMMARY_EDU".split("\t")


def four_param(x, a, b, c, d):
	return ((a - d) / (1 + (x / c) ** b)) + d
	
def prod(x):
	p = 1
	for val in x:
		p *= val
	return p

class feature:
	"""Class defines a cytological profiling feature. """
	def __init__(self, name):
		self.name = name
		self.val = dict()

	def __getitem__(self, run):
		return self.val[run]
	
	def __setitem__(self, run, value):
		self.val[run] = value
	
	def __delitem__(self, run):
		del self.val[run]
		
	def __repr__(self):
		return self.name
		
	def values(self):
		return self.val.values()
		
	def keys(self):
		return self.val.keys()
		
	def items(self):
		return self.val.items()
		
	def merge(self, feature):
		"""Function takes another feature object and merges it into this feature object if the
		names match."""
		if str(feature) == self.name:
			for run, val in feature.items():
				self.val[run] = val

class fingerprint:
	"""Class defines a cytological fingerprint for one compound/well."""
	def __init__(self, name):
		self.name = name
		self.finger = dict()

	def __getitem__(self, feat):
		return self.finger[feat]
	
	def __setitem__(self, feat, value):
		self.finger[feat] = value
		
	def __delitem__(self, feat):
		del self.finger[feat]
		
	def __repr__(self):
		return "{}".format(self.name)
		
	def values(self):
		return self.finger.values()
	
	def keys(self):
		return self.finger.keys()
		
	def items(self):
		return self.finger.items()
		
	def activity_score(self):
		return sum([val ** 2 for val in self.finger.values()])

class cp:
	"""Class defines a cytological profiling heatmap. """
	def __init__(self, cpfile=None):
		self.map = dict()
		if cpfile:
			feats, runs = self.parse_tab(open(cpfile, "U"))
			for run in runs:
				self.map[str(run)] = run
			for feat in feats:
				self.map[str(feat)] = feat

	def __getitem__(self, key):
		return self.map[key]
	
	def __setitem__(self, key, value):
		sys.stderr.write("Cannot edit single fingerprints.\n")
	
	def __delitem__(self, key):
		sys.stderr.write("Cannot edit single fingerprints.\n")
		
	def keys(self):
		return self.fingerprints()
	
	def fingerprints(self):
		return [run for run in self.map.values() if isinstance(run, fingerprint)]
	
	def features(self):
#		try:
		    return [self.map[feat] for feat in labels]
#		except KeyError:
#		    return [feat for feat in self.map.values() if isinstance(feat, feature)]

	def parse_tab(self, tab):
		"""Function takes an open tab file of CP data and inputs it into the internal
		dictionaries."""
		runs = []
		for line in tab:
			if line.strip().upper().startswith("FEATURES"):
				features = [feature(feat) for feat in line.strip().upper().split("\t")[1:]]
			else:
				finger = line.strip().split("\t")
				name = finger[0]
				runs.append(fingerprint(name))
				for feat, value in zip(features, finger[1:]):
					runs[-1][str(feat)] = feat[str(runs[-1])] = float(value)
		return features, runs
			
	def write_tab(self, tab):
		"""Function takes an open file object and writes the cp data matrix to that file as a 
		tab delimited text file.
		"""
		f = open(tab, 'w')
		runs = self.fingerprints()
		feats = labels
#		feats = self.features()
		f.write("Features\t{}\n".format("\t".join([str(feat) for feat in feats])))
		for run in runs:
			f.write("{}\t{}\n".format(str(run), "\t".join([str(run[str(feat)]) for feat in feats])))
		f.close()
		

#	def parse_scores(self, scores):
#		self.nxn = numpy.zeros((len(idruns), len(idruns))

	def get_pearson(self, id1, id2):
		return self.nxn[(self.labels.index(id1), self.labels.index(id2))]
		
		
	def pearson(self):
		"""Function returns an nxn heatmap of pearson correlations with idruns as rows and columns
		as columns. The tuple that is returned is (nxn, labels)
		"""
		idruns = self.fingerprints()
		self.labels = [str(id) for id in idruns]
		
		widgets = ['Pearson Correlations: ', Percentage(), ' ', Bar(marker=RotatingMarker()), ' ',
				ETA(), ' ', FileTransferSpeed()]
		pbar = ProgressBar(widgets=widgets, maxval=len(idruns)).start()
		
		self.nxn = numpy.zeros((len(idruns), len(idruns)))
		for ind1, id1 in enumerate(idruns):
			for ind2, id2 in enumerate(idruns):
				self.nxn[(ind1,ind2)] = pearsonr(id1.values(), id2.values())[0]
			pbar.update(ind1)
		pbar.finish()
	
	def add_tab(self, tab):
		"""Function takes an open tab file of CP data and appends it to the internal
		dictionaries."""
		feats, runs = zip(*self.parse_tab(tab))
		for run in runs:
			self.map[str(run)] = run
		for feat in feats:
			if str(feat) in self.map:
				self.map[str(feat)].merge(feat)
			else:
				self.map[str(feat)] = feat
				
	def anticluster(self, idrun, pmax=0, fraction=5, limit=None):
		aruns = []
		for ind, pear in enumerate(self.nxn[self.labels.index(idrun)]):
			if pear <= pmax and self.labels[ind][:-1] not in [id[:-1] for id in self.cruns]:
				aruns.append(self.labels[ind])
		if limit:
			return aruns[::int(len(aruns)/limit)]
		return aruns[::fraction]
				

	def cluster(self, idrun, min_tolerance=0.7, max_tolerance=0.4):
		if max_tolerance != "":
			self.limitruns = []
			self.cruns = []
		for ind, pear in enumerate(self.nxn[self.labels.index(idrun)]):
			#If it's the first iteration, find the limit runs and the runs to iterate over
			if max_tolerance != "":
				if pear > max_tolerance:
					self.limitruns.append(self.labels[ind])
				if pear > min_tolerance:
					self.cruns.append(self.labels[ind])
					self.cluster(self.labels[ind], min_tolerance, "")
			#If it's not the first iteration, find more runs to iterate over
			#Only iterate over runs that haven't been found and are within the limit
			else:
				if pear > min_tolerance and self.labels[ind] not in self.cruns and self.labels[ind] in self.limitruns:
					self.cruns.append(self.labels[ind])
					self.cluster(self.labels[ind], min_tolerance, "")
		return self.cruns			
			
	def plot_activity_dilutions(self, name, plot=True):
		fingers = [f for f in self.fingerprints() if name in str(f)]
		x = [float(str(f).split("_")[-1]) for f in fingers]
		print x
		y = [f.activity_score() for f in fingers]
		print y
		vals = None
		xtol = -6
		while vals == None:
			if not plot:
				break
			try:
				vals, cov = curve_fit(four_param, x, y, xtol=10**xtol)
				cov = map(prod, cov)
			except RuntimeError:
				xtol += 1
		
		if plot:
			yn = [four_param(xi, *vals) for xi in x]
			plt.scatter(x, yn, c='r', marker="+")
#		plt.scatter([vals[2]], [four_param(vals[2], *vals)], c="r", marker="8")
		plt.scatter(x, y)
#		plt.text(min(x), min(y), """Vals:\n a:{}\n b:{}\n c:{}\n d:{}\nCOV:\n a:{}\n b:{}\n c:{}\n d:{}\nSCORE:{}\nERROR: {}""".\
#				format(vals[0], vals[1], vals[2], vals[3], cov[0], cov[1], cov[2], cov[3], prod(cov), 10**xtol))
#		plt.xscale('log')
		plt.savefig(name + "_dilutions.pdf")
		plt.close()
		
	def plot_parameter_dilutions(self, param, name):
		fingers = self.fingerprints()
		x = [f.dilution for f in fingers]
		y = [f[param] for f in fingers]
		plt.scatter(x, y)
		plt.xscale('log')
		plt.savefig(name + "_" + param + "_dilution.pdf")
		plt.close()
	
	def plot_activity(self, name):
		fingers = self.fingerprints()
		x = range(len(fingers))
		y = sorted([finger.activity_score() for finger in fingers])
		f, (ax1, ax2) = plt.subplots(1, 2, sharey=False)
		ax1.scatter(x, y)
		ax2.hist(y, 30)
		plt.savefig(name + "_activity.pdf")
		plt.close()
		
	def plot_parameter(self, param):
		y = sorted(self[param].values())
		x = range(len(y))
		f, (ax1, ax2) = plt.subplots(1, 2, sharey=False)
		ax1.scatter(x, y)
		ax2.hist(y, 30)
		plt.savefig(param + "_plot.pdf")
		plt.close()
		for pair in sorted(self[param].items(), key=lambda p:p[1]):
			print "{}, {:4f}".format(*pair)